/* The following code was generated by JFlex 1.4.3 on 3/07/24 16:07 */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/07/24 16:07 from the specification file
 * <tt>C:/Users/SARA/eclipse-workspace/ProyectoCobol/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\4\2\0\1\3\22\0\1\17\11\0\1\5\1\34"+
    "\1\40\1\26\1\37\1\35\12\2\3\0\1\36\3\0\1\15\1\1"+
    "\1\14\1\7\1\10\1\13\1\24\1\1\1\6\1\1\1\30\1\32"+
    "\1\25\1\11\1\16\1\22\1\1\1\23\1\21\1\12\1\31\1\20"+
    "\1\27\1\1\1\33\1\1\4\0\1\1\1\0\32\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\1\1\2\1\3\1\1\1\2\1\1\1\2\1\1"+
    "\1\2\1\1\1\2\1\1\1\2\1\1\1\2\1\1"+
    "\1\4\1\2\1\5\1\6\1\7\1\10\6\6\1\11"+
    "\1\6\1\12\1\13\1\14\1\15\1\16\33\6\1\5"+
    "\2\6\1\5\7\6\1\17\5\6\1\20\1\6\1\21"+
    "\6\6\1\22\1\6\2\11\7\6\1\5\1\23\12\6"+
    "\1\24\5\6\1\5\4\6\1\5\4\6\1\25\11\6"+
    "\1\26\1\27";

  private static int [] zzUnpackAction() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\143\0\204\0\245\0\306\0\347"+
    "\0\u0108\0\u0129\0\u014a\0\u016b\0\u018c\0\u01ad\0\u01ce\0\u01ef"+
    "\0\u0210\0\u0231\0\u0252\0\u0273\0\u0231\0\u0294\0\u0231\0\u0231"+
    "\0\u02b5\0\u02d6\0\u02f7\0\u0318\0\u0339\0\u035a\0\u0231\0\u037b"+
    "\0\u0231\0\u0231\0\u0231\0\u0231\0\u0231\0\u039c\0\u03bd\0\u03de"+
    "\0\u03ff\0\u0420\0\u0441\0\u0462\0\u0483\0\u04a4\0\u04c5\0\u04e6"+
    "\0\u0507\0\u0528\0\u0549\0\u056a\0\u058b\0\u05ac\0\u05cd\0\u05ee"+
    "\0\u060f\0\u0630\0\u0651\0\u0672\0\u0693\0\u06b4\0\u06d5\0\u06f6"+
    "\0\u0717\0\u0738\0\u0759\0\u077a\0\u079b\0\u07bc\0\u07dd\0\u07fe"+
    "\0\u081f\0\u0840\0\u0861\0\u0294\0\u0882\0\u08a3\0\u08c4\0\u08e5"+
    "\0\u0906\0\u0294\0\u0927\0\u0294\0\u0948\0\u0969\0\u098a\0\u09ab"+
    "\0\u09cc\0\u09ed\0\u0294\0\u0a0e\0\u0a2f\0\u0a50\0\u0a71\0\u0a92"+
    "\0\u0ab3\0\u0ad4\0\u0af5\0\u0b16\0\u0b37\0\u0b58\0\u039c\0\u0b79"+
    "\0\u0b9a\0\u0bbb\0\u0bdc\0\u0bfd\0\u0c1e\0\u0c3f\0\u0c60\0\u0c81"+
    "\0\u0ca2\0\u0294\0\u0cc3\0\u0ce4\0\u0d05\0\u0d26\0\u0d47\0\u0d68"+
    "\0\u0d89\0\u0daa\0\u0dcb\0\u0dec\0\u0e0d\0\u0e2e\0\u0e4f\0\u0e70"+
    "\0\u0e91\0\u0294\0\u0eb2\0\u0ed3\0\u0ef4\0\u0f15\0\u0f36\0\u0f57"+
    "\0\u0f78\0\u0f99\0\u0fba\0\u0294\0\u0294";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\3\3\1\4\1\5\12\3\1\4\21\3\3\6\1\7"+
    "\1\5\12\6\1\7\21\6\4\3\1\0\37\3\1\4"+
    "\1\0\12\3\1\4\21\3\41\0\4\10\1\0\37\10"+
    "\1\11\1\0\12\10\1\11\21\10\4\12\1\0\37\12"+
    "\1\13\1\0\12\12\1\13\21\12\4\14\1\0\37\14"+
    "\1\15\1\0\12\14\1\15\21\14\4\16\1\0\37\16"+
    "\1\17\1\0\12\16\1\17\21\16\4\20\1\0\37\20"+
    "\1\21\1\0\12\20\1\21\21\20\4\22\1\0\1\23"+
    "\36\22\1\24\1\0\1\23\11\22\1\24\21\22\1\25"+
    "\1\26\1\27\1\25\1\0\1\30\1\31\1\32\4\26"+
    "\1\33\1\34\1\26\1\25\1\26\1\35\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\4\23\1\0\34\23\1\25\1\26\1\27\1\24\1\0"+
    "\1\30\1\31\1\32\4\26\1\33\1\34\1\26\1\24"+
    "\1\26\1\35\1\36\3\26\1\37\1\40\4\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\32\4\26\1\33\1\34\1\26\1\25"+
    "\1\26\1\35\1\36\3\26\1\37\1\40\4\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\46\4\26\1\33\1\34\1\26\1\25"+
    "\1\26\1\35\1\36\3\26\1\37\1\40\4\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\47\1\32\4\26\1\33\1\50\1\26\1\25"+
    "\1\26\1\35\1\36\3\26\1\37\1\40\4\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\32\4\26\1\33\1\34\1\51\1\25"+
    "\1\26\1\35\1\36\3\26\1\37\1\40\4\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\32\4\26\1\52\1\34\1\26\1\25"+
    "\1\26\1\35\1\36\3\26\1\37\1\40\4\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\32\2\26\1\53\1\26\1\33\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\3\26\1\37\1\40"+
    "\4\26\1\41\1\42\1\43\1\44\1\45\1\25\2\26"+
    "\1\25\1\0\1\30\1\31\1\32\4\26\1\33\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\1\54\2\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\31\1\32\4\26\1\33"+
    "\1\34\1\55\1\25\1\26\1\35\1\36\3\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\47\1\32\1\56\3\26"+
    "\1\33\1\50\1\26\1\25\1\26\1\35\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\31\1\46\4\26"+
    "\1\33\1\34\1\26\1\25\1\26\1\57\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\31\1\32\2\26"+
    "\1\60\1\26\1\52\1\34\1\26\1\25\1\26\1\35"+
    "\1\36\3\26\1\37\1\40\4\26\1\41\1\42\1\43"+
    "\1\44\1\45\1\25\2\26\1\25\1\0\1\30\1\31"+
    "\1\32\4\26\1\33\1\34\1\26\1\25\1\26\1\35"+
    "\1\36\2\26\1\61\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\32\4\26\1\62\1\34\1\51\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\32\4\26\1\33\1\34\1\63\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\32\4\26\1\33\1\34\1\64\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\32\4\26\1\33\1\34\1\26\1\25\1\26"+
    "\1\35\1\36\1\65\2\26\1\37\1\40\4\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\32\1\26\1\66\2\26\1\33\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\3\26\1\37\1\40"+
    "\4\26\1\41\1\42\1\43\1\44\1\45\1\25\2\26"+
    "\1\25\1\0\1\30\1\31\1\32\2\26\1\53\1\26"+
    "\1\33\1\34\1\26\1\25\1\26\1\35\1\67\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\31\1\32\4\26"+
    "\1\33\1\70\1\26\1\25\1\26\1\35\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\31\1\32\4\26"+
    "\1\33\1\34\1\26\1\25\1\26\1\35\1\71\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\31\1\32\1\72"+
    "\3\26\1\33\1\34\1\51\1\25\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\32"+
    "\4\26\1\33\1\34\1\26\1\25\1\26\1\35\1\73"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\32"+
    "\4\26\1\74\1\34\1\26\1\25\1\26\1\35\1\36"+
    "\1\26\1\75\1\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\32\4\26\1\33\1\34\1\26\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\1\76\3\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\32\2\26\1\77\1\26\1\33\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\3\26\1\37\1\40"+
    "\4\26\1\41\1\42\1\43\1\44\1\45\1\25\2\26"+
    "\1\25\1\0\1\30\1\31\1\32\4\26\1\33\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\1\54\2\26\1\37"+
    "\1\40\2\26\1\100\1\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\32"+
    "\4\26\1\52\1\34\1\26\1\101\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\32"+
    "\4\26\1\33\1\34\1\26\1\25\1\26\1\35\1\36"+
    "\1\54\2\26\1\37\1\40\1\26\1\102\2\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\32\4\26\1\33\1\34\1\26\1\25"+
    "\1\26\1\35\1\103\3\26\1\37\1\40\4\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\32\4\26\1\33\1\34\1\26\1\104"+
    "\1\26\1\35\1\36\1\54\2\26\1\37\1\40\4\26"+
    "\1\41\1\42\1\43\1\44\1\45\1\25\2\26\1\25"+
    "\1\0\1\30\1\31\1\32\1\105\3\26\1\33\1\34"+
    "\1\51\1\25\1\26\1\35\1\36\3\26\1\37\1\40"+
    "\4\26\1\41\1\42\1\43\1\44\1\45\1\25\2\26"+
    "\1\25\1\0\1\30\1\31\1\32\4\26\1\33\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\1\106\2\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\107\1\32\4\26\1\33"+
    "\1\34\1\26\1\25\1\26\1\35\1\36\3\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\110\1\32\4\26\1\33"+
    "\1\34\1\26\1\25\1\26\1\35\1\36\3\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\31\1\32\4\26\1\33"+
    "\1\111\1\26\1\25\1\26\1\35\1\36\3\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\1\26\1\27\1\25\1\0\1\30\1\31\1\112\4\26"+
    "\1\33\1\34\1\26\1\25\1\26\1\35\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\31\1\32\2\26"+
    "\1\113\1\26\1\33\1\34\1\26\1\25\1\26\1\35"+
    "\1\36\3\26\1\37\1\40\4\26\1\41\1\42\1\43"+
    "\1\44\1\45\1\25\2\26\1\25\1\0\1\30\1\31"+
    "\1\32\2\26\1\114\1\26\1\33\1\34\1\26\1\25"+
    "\1\26\1\35\1\36\1\54\2\26\1\37\1\40\4\26"+
    "\1\41\1\42\1\43\1\44\1\45\1\25\1\26\1\27"+
    "\1\25\1\0\1\30\1\31\1\32\4\26\1\33\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\1\115\2\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\31\1\116\4\26\1\33"+
    "\1\34\1\26\1\25\1\26\1\35\1\36\3\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\31\1\32\4\26\1\33"+
    "\1\117\1\26\1\25\1\26\1\35\1\36\3\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\31\1\46\1\26\1\120"+
    "\2\26\1\33\1\34\1\26\1\25\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\46"+
    "\3\26\1\121\1\33\1\34\1\26\1\25\1\26\1\35"+
    "\1\36\3\26\1\37\1\40\4\26\1\41\1\42\1\43"+
    "\1\44\1\45\1\25\2\26\1\25\1\0\1\30\1\31"+
    "\1\32\4\26\1\52\1\34\1\26\1\25\1\26\1\35"+
    "\1\36\3\26\1\37\1\40\3\26\1\122\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\123\1\32\4\26\1\33\1\50\1\26\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\32\1\124\3\26\1\33\1\34\1\26\1\25"+
    "\1\26\1\35\1\36\3\26\1\37\1\40\4\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\32\4\26\1\33\1\34\1\26\1\25"+
    "\1\26\1\35\1\36\3\26\1\37\1\40\1\26\1\125"+
    "\2\26\1\41\1\42\1\43\1\44\1\45\1\25\2\26"+
    "\1\25\1\0\1\30\1\47\1\32\4\26\1\33\1\50"+
    "\1\26\1\25\1\26\1\35\1\36\3\26\1\37\1\40"+
    "\1\26\1\126\2\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\31\1\32\4\26"+
    "\1\52\1\34\1\26\1\25\1\26\1\35\1\36\2\26"+
    "\1\127\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\32"+
    "\4\26\1\33\1\34\1\26\1\25\1\26\1\35\1\36"+
    "\1\26\1\130\1\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\131\1\32\4\26\1\33\1\34\1\26\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\46\4\26\1\33\1\34\1\26\1\25\1\132"+
    "\1\57\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\32\1\26\1\133\2\26\1\33\1\34\1\26"+
    "\1\25\1\26\1\35\1\36\3\26\1\37\1\40\4\26"+
    "\1\41\1\42\1\43\1\44\1\45\1\25\2\26\1\25"+
    "\1\0\1\30\1\31\1\32\4\26\1\33\1\34\1\26"+
    "\1\25\1\26\1\35\1\36\1\134\2\26\1\37\1\40"+
    "\4\26\1\41\1\42\1\43\1\44\1\45\1\25\2\26"+
    "\1\25\1\0\1\30\1\31\1\32\4\26\1\33\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\3\26\1\135\1\40"+
    "\4\26\1\41\1\42\1\43\1\44\1\45\1\25\2\26"+
    "\1\25\1\0\1\30\1\31\1\32\4\26\1\33\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\3\26\1\136\1\40"+
    "\4\26\1\41\1\42\1\43\1\44\1\45\1\25\2\26"+
    "\1\25\1\0\1\30\1\31\1\46\4\26\1\137\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\3\26\1\37\1\40"+
    "\4\26\1\41\1\42\1\43\1\44\1\45\1\25\2\26"+
    "\1\25\1\0\1\30\1\140\1\32\4\26\1\33\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\3\26\1\37\1\40"+
    "\4\26\1\41\1\42\1\43\1\44\1\45\1\25\2\26"+
    "\1\25\1\0\1\30\1\31\1\32\1\141\3\26\1\33"+
    "\1\34\1\26\1\25\1\26\1\35\1\36\3\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\1\26\1\27\1\25\1\0\1\30\1\142\1\32\4\26"+
    "\1\33\1\34\1\26\1\25\1\26\1\35\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\1\26\1\27\1\25\1\0\1\30\1\31\1\32"+
    "\4\26\1\33\1\34\1\26\1\25\1\26\1\143\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\32"+
    "\4\26\1\33\1\144\1\51\1\25\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\46"+
    "\4\26\1\33\1\34\1\26\1\25\1\26\1\145\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\32"+
    "\4\26\1\33\1\34\1\26\1\146\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\147"+
    "\4\26\1\33\1\34\1\26\1\25\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\32"+
    "\2\26\1\150\1\26\1\33\1\34\1\26\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\32\2\26\1\151\1\26\1\52\1\34\1\26"+
    "\1\25\1\26\1\35\1\36\3\26\1\37\1\40\4\26"+
    "\1\41\1\42\1\43\1\44\1\45\1\25\2\26\1\25"+
    "\1\0\1\30\1\152\1\32\2\26\1\53\1\26\1\33"+
    "\1\34\1\26\1\25\1\26\1\35\1\36\3\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\1\26\1\27\1\25\1\0\1\30\1\31\1\153\4\26"+
    "\1\33\1\34\1\26\1\25\1\26\1\35\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\31\1\32\4\26"+
    "\1\33\1\34\1\154\1\25\1\26\1\35\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\155\1\32\4\26"+
    "\1\33\1\34\1\26\1\25\1\26\1\35\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\31\1\46\4\26"+
    "\1\33\1\34\1\156\1\25\1\26\1\35\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\157\1\32\4\26"+
    "\1\33\1\50\1\26\1\25\1\26\1\35\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\2\26\1\25\1\0\1\30\1\31\1\32\4\26"+
    "\1\33\1\34\1\26\1\25\1\26\1\35\1\73\1\160"+
    "\2\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\46"+
    "\4\26\1\33\1\34\1\161\1\25\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\32"+
    "\1\26\1\162\2\26\1\33\1\34\1\26\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\46\4\26\1\33\1\34\1\26\1\25\1\163"+
    "\1\57\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\32\4\26\1\33\1\164\1\26\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\32\1\26\1\165\2\26\1\33\1\34\1\26"+
    "\1\25\1\26\1\35\1\36\3\26\1\37\1\40\4\26"+
    "\1\41\1\42\1\43\1\44\1\45\1\25\2\26\1\25"+
    "\1\0\1\30\1\166\1\32\4\26\1\33\1\34\1\26"+
    "\1\25\1\26\1\35\1\36\3\26\1\37\1\40\4\26"+
    "\1\41\1\42\1\43\1\44\1\45\1\25\2\26\1\25"+
    "\1\0\1\30\1\31\1\32\4\26\1\52\1\34\1\26"+
    "\1\25\1\26\1\35\1\36\1\26\1\167\1\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\31\1\32\4\26\1\33"+
    "\1\34\1\26\1\170\1\26\1\35\1\36\3\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\31\1\46\4\26\1\33"+
    "\1\34\1\26\1\25\1\26\1\171\1\36\3\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\31\1\32\1\172\3\26"+
    "\1\33\1\34\1\26\1\25\1\26\1\35\1\36\3\26"+
    "\1\37\1\40\4\26\1\41\1\42\1\43\1\44\1\45"+
    "\1\25\1\26\1\27\1\25\1\0\1\30\1\31\1\173"+
    "\4\26\1\33\1\34\1\26\1\25\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\174\1\32"+
    "\2\26\1\53\1\26\1\33\1\34\1\26\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\32\4\26\1\33\1\34\1\26\1\175\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\176\1\32\4\26\1\33\1\50\1\26\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\31\1\46\4\26\1\33\1\34\1\177\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\1\26\1\27\1\25\1\0"+
    "\1\30\1\31\1\32\4\26\1\33\1\34\1\26\1\25"+
    "\1\26\1\200\1\36\3\26\1\37\1\40\4\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\46\4\26\1\33\1\34\1\26\1\25"+
    "\1\201\1\57\1\36\3\26\1\37\1\40\4\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\25\2\26\1\25\1\0"+
    "\1\30\1\31\1\32\1\26\1\202\2\26\1\33\1\34"+
    "\1\26\1\25\1\26\1\35\1\36\3\26\1\37\1\40"+
    "\4\26\1\41\1\42\1\43\1\44\1\45\1\25\2\26"+
    "\1\25\1\0\1\30\1\31\1\32\1\203\1\26\1\53"+
    "\1\26\1\33\1\34\1\26\1\25\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\204\1\32"+
    "\4\26\1\33\1\34\1\26\1\25\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\32"+
    "\4\26\1\205\1\34\1\26\1\25\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\46"+
    "\4\26\1\33\1\34\1\26\1\25\1\26\1\206\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45\1\25\2\26\1\25\1\0\1\30\1\31\1\32"+
    "\2\26\1\207\1\26\1\33\1\34\1\51\1\25\1\26"+
    "\1\35\1\36\3\26\1\37\1\40\4\26\1\41\1\42"+
    "\1\43\1\44\1\45\1\25\2\26\1\25\1\0\1\30"+
    "\1\210\1\32\2\26\1\53\1\26\1\33\1\34\1\26"+
    "\1\25\1\26\1\35\1\36\3\26\1\37\1\40\4\26"+
    "\1\41\1\42\1\43\1\44\1\45\1\25\2\26\1\25"+
    "\1\0\1\30\1\211\1\32\4\26\1\33\1\34\1\26"+
    "\1\25\1\26\1\35\1\36\3\26\1\37\1\40\4\26"+
    "\1\41\1\42\1\43\1\44\1\45\1\25\2\26\1\25"+
    "\1\0\1\30\1\31\1\46\4\26\1\33\1\34\1\212"+
    "\1\25\1\26\1\35\1\36\3\26\1\37\1\40\4\26"+
    "\1\41\1\42\1\43\1\44\1\45\1\25\2\26\1\25"+
    "\1\0\1\30\1\31\1\46\4\26\1\33\1\34\1\213"+
    "\1\25\1\26\1\35\1\36\3\26\1\37\1\40\4\26"+
    "\1\41\1\42\1\43\1\44\1\45\1\25\2\26\1\25"+
    "\1\0\1\30\1\31\1\32\1\26\1\214\2\26\1\33"+
    "\1\34\1\26\1\25\1\26\1\35\1\36\3\26\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\1\45\1\25"+
    "\2\26\1\25\1\0\1\30\1\31\1\32\1\26\1\215"+
    "\2\26\1\33\1\34\1\26\1\25\1\26\1\35\1\36"+
    "\3\26\1\37\1\40\4\26\1\41\1\42\1\43\1\44"+
    "\1\45";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4059];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\1\1\11\210\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 98) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 13: 
          { lexeme=yytext().substring(yytext().indexOf(".")); return Punto;
          }
        case 24: break;
        case 6: 
          { lexeme=yytext().substring(7); return Identificador;
          }
        case 25: break;
        case 15: 
          { lexeme=yytext().substring(yytext().indexOf("ACCEPT")); return ACCEPT;
          }
        case 26: break;
        case 10: 
          { lexeme=yytext().substring(yytext().indexOf("+")); return Suma;
          }
        case 27: break;
        case 17: 
          { lexeme=yytext().substring(yytext().indexOf("COMPUTE")); return COMPUTE;
          }
        case 28: break;
        case 8: 
          { lexeme=yytext().substring(yytext().indexOf("*")); return Multiplicacion;
          }
        case 29: break;
        case 9: 
          { lexeme=yytext().substring(yytext().indexOf("-")); return Resta;
          }
        case 30: break;
        case 18: 
          { lexeme=yytext().substring(yytext().indexOf("STOP RUN")); return STOP_RUN;
          }
        case 31: break;
        case 3: 
          { return Linea;
          }
        case 32: break;
        case 7: 
          { lexeme=yytext().substring(7); return Numero;
          }
        case 33: break;
        case 4: 
          { /* Línea con asterisco en la columna 7 */
          }
        case 34: break;
        case 21: 
          { lexeme=yytext().substring(yytext().indexOf("PROCEDURE DIVISION")); return PROCEDURE_DIVISION;
          }
        case 35: break;
        case 12: 
          { lexeme=yytext().substring(yytext().indexOf("=")); return Igual;
          }
        case 36: break;
        case 1: 
          { /* Ignorar cualquier cosa antes de la columna 8 */
          }
        case 37: break;
        case 23: 
          { lexeme=yytext().substring(yytext().indexOf("WORKING-STORAGE SECTION")); return WORKING_STORAGE_SECTION;
          }
        case 38: break;
        case 22: 
          { lexeme=yytext().substring(yytext().indexOf("IDENTIFICATION DIVISION")); return IDENTIFICATION_DIVISION;
          }
        case 39: break;
        case 14: 
          { lexeme=yytext().substring(yytext().indexOf(",")); return Coma;
          }
        case 40: break;
        case 5: 
          { return ERROR;
          }
        case 41: break;
        case 16: 
          { lexeme=yytext().substring(yytext().indexOf("DISPLAY")); return DISPLAY;
          }
        case 42: break;
        case 20: 
          { lexeme=yytext().substring(yytext().indexOf("DATA DIVISION")); return DATA_DIVISION;
          }
        case 43: break;
        case 19: 
          { lexeme=yytext().substring(yytext().indexOf("PROGRAM-ID")); return PROGRAM_ID;
          }
        case 44: break;
        case 11: 
          { lexeme=yytext().substring(yytext().indexOf("/")); return Division;
          }
        case 45: break;
        case 2: 
          { 
          }
        case 46: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
