
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jul 05 00:27:20 PET 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TipoSignoNumero = 16;
  public static final int If = 23;
  public static final int Compute = 12;
  public static final int Diferente = 32;
  public static final int Else = 24;
  public static final int TipoEntero = 13;
  public static final int WorkingStorageSection = 6;
  public static final int Punto = 33;
  public static final int NumeroDecimal = 36;
  public static final int Pic = 25;
  public static final int Division = 22;
  public static final int Display = 10;
  public static final int Cadena = 37;
  public static final int EOF = 0;
  public static final int MayorQue = 29;
  public static final int Value = 26;
  public static final int error = 1;
  public static final int ProgramId = 5;
  public static final int ProcedureDivision = 4;
  public static final int Accept = 11;
  public static final int TipoAlfabeto = 15;
  public static final int ERROR = 38;
  public static final int IdentificationDivision = 2;
  public static final int MenorIgual = 30;
  public static final int TipoAlfanumerico = 14;
  public static final int Identificador = 34;
  public static final int DataDivision = 3;
  public static final int StopRun = 9;
  public static final int Resta = 20;
  public static final int MenorQue = 28;
  public static final int MayorIgual = 31;
  public static final int ValorEspecial = 8;
  public static final int ParentesisC = 18;
  public static final int Multiplicacion = 21;
  public static final int ParentesisA = 17;
  public static final int Numero = 35;
  public static final int Suma = 19;
  public static final int Igual = 27;
  public static final int Nivel = 7;
}

