
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jul 04 12:23:43 PET 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 6;
  public static final int Parentesis_c = 14;
  public static final int Parentesis_a = 13;
  public static final int Suma = 9;
  public static final int Numero = 20;
  public static final int ERROR = 21;
  public static final int Identificador = 19;
  public static final int Int = 4;
  public static final int Llave_c = 16;
  public static final int Llave_a = 15;
  public static final int P_coma = 18;
  public static final int T_dato = 3;
  public static final int Main = 17;
  public static final int EOF = 0;
  public static final int Division = 12;
  public static final int Resta = 10;
  public static final int If = 5;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Igual = 8;
  public static final int While = 7;
  public static final int Multiplicacion = 11;
}

