
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jul 04 19:10:45 PET 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MayorQue = 24;
  public static final int Else = 19;
  public static final int ProcedureDivision = 4;
  public static final int ValorEspecial = 9;
  public static final int Nivel = 7;
  public static final int Suma = 14;
  public static final int Numero = 30;
  public static final int WorkingStorageSection = 6;
  public static final int ProgramId = 5;
  public static final int Compute = 13;
  public static final int ERROR = 33;
  public static final int TipoDato = 8;
  public static final int Display = 11;
  public static final int Identificador = 29;
  public static final int Cadena = 32;
  public static final int EOF = 0;
  public static final int NumeroDecimal = 31;
  public static final int Division = 17;
  public static final int Accept = 12;
  public static final int MenorIgual = 25;
  public static final int If = 18;
  public static final int Resta = 15;
  public static final int error = 1;
  public static final int Punto = 28;
  public static final int MayorIgual = 26;
  public static final int IdentificationDivision = 2;
  public static final int Igual = 22;
  public static final int DataDivision = 3;
  public static final int Multiplicacion = 16;
  public static final int MenorQue = 23;
  public static final int Pic = 20;
  public static final int Value = 21;
  public static final int StopRun = 10;
  public static final int Diferente = 27;
}

